services:
  postgres:
    image: postgres:16
    container_name: sistema_biblioteca_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: biblioteca
      POSTGRES_PASSWORD: biblioteca
      POSTGRES_DB: sistema_biblioteca
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
